In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score

def boosting(file_names):
    df_list = [pd.read_excel(arquivo) for arquivo in file_names]
    z_preds = [df['Z_pred'].values.reshape(-1, 1) for df in df_list]
    Z_pred_total = np.hstack(z_preds)
    print(f"Z_pred_total: {Z_pred_total}")
    Z_pred_sum = np.sum(Z_pred_total, axis=1).reshape(-1, 1)

    df = pd.read_excel("1000_model_12_6_0.xlsx")
    Z = df['Z'].values.reshape(-1, 1)

    mse_sup = np.mean((Z - Z_pred_sum) ** 2)
    r2_sup = r2_score(Z, Z_pred_sum)

    print(f"mse: {mse_sup}")
    return mse_sup, r2_sup
file_names= ["1000_model_23_6_4.xlsx", "1000_model_12_6_0.xlsx", "1000_model_13_2_14.xlsx", "1000_model_29_7_11.xlsx", "1000_model_33_7_2.xlsx"]
result= boosting(file_names)


Z_pred_total: [[-3.53625035 -0.60401952 -1.12609267  2.72602463  0.06894893]
 [-3.79460168 -0.74503672 -1.11051702  2.47231579  0.32069555]
 [-4.05666542 -0.84535789 -1.10375726  2.21147156  0.58572054]
 ...
 [ 1.22910178  0.22320603  0.36216176 -1.09213638 -0.16894415]
 [ 1.46657228  0.22454627  0.29336759 -1.30422044  0.09791011]
 [ 1.68168199  0.24491258  0.23644593 -1.51804709  0.33741766]]
mse: 1.5810441108593092
