In [5]:
import pandas as pd
import numpy as np
from sklearn.metrics import r2_score

def boosting(file_names):
    df_list = [pd.read_excel(arquivo) for arquivo in file_names]
    z_preds = [df['Z_pred'].values.reshape(-1, 1) for df in df_list]
    Z_pred_total = np.hstack(z_preds)
    print(f"Z_pred_total: {Z_pred_total}")
    Z_pred_sum = np.sum(Z_pred_total, axis=1).reshape(-1, 1)

    df = pd.read_excel("1000_model_12_6_0.xlsx")
    Z = df['Z'].values.reshape(-1, 1)

    mse_sup = np.mean((Z - Z_pred_sum) ** 2)
    r2_sup = r2_score(Z, Z_pred_sum)

    print(f"mse: {mse_sup}")
    return mse_sup, r2_sup
file_names= ["1000_model_1_8_24.xlsx", "1000_model_12_6_0.xlsx", "1000_model_13_2_14.xlsx", "1000_model_15_2_13.xlsx", "1000_model_15_2_13_4.xlsx"]
result= boosting(file_names)


Z_pred_total: [[-0.24937797 -0.60401952 -1.12609267 -0.07958294  0.03499098]
 [-0.24201638 -0.74503672 -1.11051702 -0.02410628  0.09998433]
 [-0.23418146 -0.84535789 -1.10375726  0.03994639  0.17502485]
 ...
 [ 0.9352541   0.22320603  0.36216176 -0.29170224 -0.21351607]
 [ 0.90770447  0.22454627  0.29336759 -0.37972745 -0.31664148]
 [ 0.89409173  0.24491258  0.23644593 -0.46390787 -0.41526261]]
mse: 21.654669800667822
